### ISSUE TITLE
not executing trade

### ISSUE THREAD

**Issue by majestic1222** [thammo4/uvatradier#33]
order_response = equity_order.order(symbol='TRAW', side='buy', quantity='1', order_type='market', duration='day');

{'order': {'id': 14148825, 'status': 'ok', 'partner_id': 'f148e89a-c3b6-4f7f-8c21-4364f5f03f54'}}

appears to have executed the command properly based on results returned, but account not showing buy order

**Comment by majestic1222** [comment]
btw it works on my paper account but not the cash account

**Comment by majestic1222** [comment]
not sure where my coding is wrong, but i just decided to change sandbox in base.py to api.

**Comment by jwizenf2** [comment]
I had the same issue. Seems to be that the `EquityOrder` class is missing the `live_trade` boolean in the constructor, so it is defaulting to the sandbox API URL and not the live trading one.

**Comment by thammo4** [comment]
Hey thanks for calling this out. I just pushed the fix. If you pip update the package, the `live_trade` flag is included in the EquityOrder class
