### ISSUE TITLE
EquityOrder has .order not .place_order

### ISSUE THREAD

**Issue by yuvansundrani** [thammo4/uvatradier#36]
Hi!

Thanks for providing this API! Just wanted to let you know of a bug:

It says: `order_response = equity_order.place_order('AAPL', 'buy', 1, 'limit', 150)`

And 'equity_order' is an object of 'EquityOrder' which doesn't have a 'place_order'  method, it only has an 'order' method. 

So it should be: 'order_response = equity_order.order('AAPL', 'buy', 1, 'limit', 150)`

Cheers!

**Comment by thammo4** [comment]
Thanks for pointing this out! You're absolutely correct. There were actually a bunch of mistakes that needed cleaning up as well, so I really appreciate the heads up. I need to be more careful in the future about letting ChatGPT write README files for me
